services:
  frontend:
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/api/alerts').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 45s
